#! /bin/bash

#АВТОСТАРТ
# Конфигурация горячих клавиш BSPWM
sxhkd &
# Numlock
numlockx &
# Раскладка клавиатуры 
setxkbmap -model pc105 -layout us,ru -variant -option grp:alt_shift_toggle
# Настройка монитора (1080p @60gz)
xrandr --output HDMI-0 --mode 0x1bf --verbose --rate 60
#nitrogen --restore &
# Обои рабочего стола
variety &
# Панель Polybar с конфигом для BSPWM
polybar example -c $HOME/.config/bspwm/polybar/config.ini &
# оконный композитор picom с общей конфигурацией
picom --config $HOME/.config/bspwm/picom.conf &
xsetroot -cursor_name left_ptr &

# Пример автозапуска приложений
#conky &
#firefox &
#telegram-desktop &

#ВОРКСПЕЙСЫ
#bspc monitor -d             
bspc monitor -d                   


#РАМКИ И ГАПСЫ
bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНАЫ
bspc config presel_feedback_color "#fd2e59"

#ПРИ ПОМОЩИ ЭТОЙ ХРЕНИ МОЖНО СДЕЛАТЬ ГАПСЫ ТОЛЬКО МЕЖДУ ОКНАМИ
#bspc config window_gap $gap;
#bspc config top_padding -$(($gap+2))
#bspc config left_padding -$(($gap+2))
#bspc config right_padding -$(($gap+4))
#bspc config bottom_padding $(($PANEL_HEIGHT-$gap))



#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5
#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	     false

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true


#СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
#bspc config automatic_scheme	spiral


#ПРАВИЛА ОКОН
bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating

# ===== 1 ===== #
#bspc rule -a firefox state=floating follow=off  desktop='^1'
# ===== 2 ===== #
bspc rule -a Code follow=off desktop='^2'
bspc rule -a sublime_text follow=off desktop='^2'
# ===== 3 ===== #
bspc rule -a Brave-browser follow=off desktop='^3'
# ===== 4 ===== #
# ===== 5 ===== #
bspc rule -a Steam state=floating follow=off rectangle=1350x900+285+90 desktop='^5' 
# ===== 6 ===== #
# ===== 7 ===== #
bspc rule -a TelegramDesktop state=floating follow=off desktop='^7'
# ===== 8 ===== #
#bspc rule -a Gimp desktop=^8 follow=true
# ===== 9 ===== #
# ===== 10 ===== #

#bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
#bspc rule -a dmenu rectangle=900x22+610+90




